apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-service-deployment
  labels:
    app: front-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-service
  template:
    metadata:
      labels:
        app: front-service
    spec:
      containers:
      - name: front-service
        image: [FRONT-SERVICE-IMAGE-PUSH-LOCATION]
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 2
          failureThreshold: 1
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 2
          failureThreshold: 1 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-service-deployment
  labels:
    app: backend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-service
  template:
    metadata:
      labels:
        app: backend-service
    spec:
      containers:
      - name: backend-service
        image: [BACKEND-SERVICE-IMAGE-PUSH-LOCATION]
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: front-service-port
spec:
  type: NodePort
  selector:
    app: front-service
  ports:
    - port: 8080
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service-port
spec:
  sessionAffinity: None
  selector:
    app: backend-service
  ports:
    - port: 8080
      targetPort: 8080
      name: http
